// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq94OeuewPSb1Wfj5q69AxhMiGCO_ezuw',
    appId: '1:1071309727327:web:79b41cb4fb637c14c65dea',
    messagingSenderId: '1071309727327',
    projectId: 'loginpractica-e7628',
    authDomain: 'loginpractica-e7628.firebaseapp.com',
    storageBucket: 'loginpractica-e7628.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1HA3sb3GhjkAk5gQLXE4ZOyEnWCfYHRQ',
    appId: '1:1071309727327:android:1eacd5aee4c9dbffc65dea',
    messagingSenderId: '1071309727327',
    projectId: 'loginpractica-e7628',
    storageBucket: 'loginpractica-e7628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRzwKn8grpabZDi2U8s1kRArfCuKk5Klw',
    appId: '1:1071309727327:ios:40b77184763012cdc65dea',
    messagingSenderId: '1071309727327',
    projectId: 'loginpractica-e7628',
    storageBucket: 'loginpractica-e7628.appspot.com',
    iosClientId: '1071309727327-3g3vlkbgef5q8bej1qu8n6qr29gd9ssv.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRzwKn8grpabZDi2U8s1kRArfCuKk5Klw',
    appId: '1:1071309727327:ios:ee831081fe289a5cc65dea',
    messagingSenderId: '1071309727327',
    projectId: 'loginpractica-e7628',
    storageBucket: 'loginpractica-e7628.appspot.com',
    iosClientId: '1071309727327-spooqu1f19nvnkhcs8m90p6eltlpult3.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
